---
nextcloud_enabled: false
nextcloud_available_externally: "false"

nextcloud_image: "linuxserver/nextcloud:21"

# directories
nextcloud_data_directory: "{{ docker_home }}/nextcloud"

# network
nextcloud_port: "8080"
nextcloud_hostname: "nextcloud"

nextcloud_memory: 4g

# username / passwords
nextcloud_sql_user: "nextcloud-user"
nextcloud_sql_password: "nextcloud-pass"
nextcloud_sql_root_password: "nextcloud-secret"