---
- name: Create Openvpn-client Directories
  file:
    path: "{{ item }}"
    state: directory
    # mode: 0755
  with_items:
    - "{{ openvpn_client_data_directory }}"

- name: Copy VPN Files to Openvpn-client
  file:
    src: "{{ item }}"
    dest: "{{ openvpn_client_data_directory }}"
  with_items:
    - "{{ openvpn_client_ca_crt }}"
    - "{{ openvpn_client_client_crt }}"
    - "{{ openvpn_client_client_key }}"
    - "{{ openvpn_client_vpn_conf }}"


- name: Create Openvpn-client Docker Container
  docker_container:
    name: "{{ openvpn_client_name }}"
    image: "{{ openvpn_client_image }}"
    pull: true
    volumes:
      - "{{ openvpn_client_data_directory }}:/vpn:rw"
    domainname: "{{ openvpn_client_domain }}"
    hostname: "{{ openvpn_client_hostname }}"
    network_mode: "{{ openvpn_client_network_mode }}"
    devices: "/dev/net/tun"
    capabilities: "NET_ADMIN"
    command: "'-f' '' '-a' '{{ openvpn_client_username }};{{ openvpn_client_password }}'"
    ports:
      - "{{ openvpn_client_port_deluge }}"
    env:
      TZ: "{{ nasible_timezone }}"
      # PUID: "{{ openvpn_client_user_id }}"
      # PGID: "{{ openvpn_client_group_id }}"
    cpus: "{{ openvpn_client_cpus }}"
    memory: "{{ openvpn_client_memory }}"
    restart_policy: "{{ openvpn_client_restarts }}"
