# Project information
site_name: 'NASible'
site_description: 'Build a fully functional NAS with an Ubuntu box and this playbook'
site_author: 'PurpleNinja225'

# Configuration
theme:
  name: 'cayman'
  language: 'en'


# Repository
repo_name: 'PurpleNinja225/NASible'
repo_url: 'https://github.com/PurpleNinja225/NASible'

# Copyright
copyright: 'Copyright &copy; 2021 NASible'

# Customization
extra:
  manifest: 'manifest.webmanifest'
  social:
    - icon: 'fontawesome/brands/github-alt'
