---
- hosts: all
  become: yes
  pre_tasks:
    - import_tasks: tasks/users.yml
      tags: users

  roles:

    #############################################################################
    ### Requirements ############################################################
    #############################################################################

    - role: bertvv.samba
      tags:
        - samba
        - skip_ansible_lint

    - role: geerlingguy.nfs
      tags:
        - nfs
        - skip_ansible_lint

    - role: geerlingguy.docker
      tags:
        - docker
        - skip_ansible_lint

    #############################################################################
    ### NASible Roles ###########################################################
    #############################################################################

    - role: nasible-general
      tags:
        - nasible-general
        - nasible

    - role: nasible-docker
      tags:
        - nasible-docker
        - nasible

    #############################################################################
    ### Applications ############################################################
    #############################################################################

    - role: airsonic
      tags:
        - airsonic
      when: (airsonic_enabled | default(False))

    - role: bazarr
      tags:
        - bazarr
      when: (bazarr_enabled | default(False))

    - role: bitwarden
      tags:
        - bitwarden
      when: (bitwarden_enabled | default(False))

    - role: calibre_web
      tags:
        - calibre_web
      when: (calibre_web_enabled | default(False))

    - role: cloudcmd
      tags:
        - cloudcmd
      when: (cloudcmd_enabled | default(False))

    - role: cloudflare_ddns
      tags:
        - cloudflare_ddns
      when: (cloudflare_ddns_enabled | default(False))

    - role: couchpotato
      tags:
        - couchpotato
      when: (couchpotato_enabled | default(False))

    - role: deluge
      tags:
        - deluge
      when: (deluge_enabled | default(False))

    - role: dokuwiki
      tags:
        - dokuwiki
      when: (dokuwiki_enabled | default(False))

    - role: duplicati
      tags:
        - duplicati
      when: (duplicati_enabled | default(False))

    - role: emby
      tags:
        - emby
      when: (emby_enabled | default(False))

    - role: firefly
      tags:
        - firefly
      when: (firefly_enabled | default(False))

    - role: get_iplayer
      tags:
        - get_iplayer
      when: (get_iplayer_enabled | default(False))

    - role: gitea
      tags:
        - gitea
      when: (gitea_enabled | default(False))

    - role: gitlab
      tags:
        - gitlab
      when: (gitlab_enabled | default(False))

    - role: glances
      tags:
        - glances
      when: (glances_enabled | default(False))

    - role: gotify
      tags:
        - gotify
      when: (gotify_enabled | default(False))

    - role: grafana_stats
      tags:
        - grafana_stats
      when: (grafana_stats_enabled | default(False))

    - role: guacamole
      tags:
        - guacamole
      when: (guacamole_enabled | default(False))

    - role: heimdall
      tags:
        - heimdall
      when: (heimdall_enabled | default(False))

    - role: homeassistant
      tags:
        - homeassistant
      when: (homeassistant_enabled | default(False))

    - role: homebridge
      tags:
        - homebridge
      when: (homebridge_enabled | default(False))

    - role: jackett
      tags:
        - jackett
      when: (jackett_enabled | default(False))

    - role: jellyfin
      tags:
        - jellyfin
      when: (jellyfin_enabled | default(False))

    - role: joomla
      tags:
        - joomla
      when: (joomla_enabled | default(False))

    - role: krusader
      tags:
        - krusader
      when: (krusader_enabled | default(False))

    - role: lidarr
      tags:
        - lidarr
      when: (lidarr_enabled | default(False))

    - role: minidlna
      tags:
        - minidlna
      when: (minidlna_enabled | default(False))

    - role: miniflux
      tags:
        - miniflux
      when: (miniflux_enabled | default(False))

    - role: mosquitto
      tags:
        - mosquitto
      when: (mosquitto_enabled | default(False))

    - role: mylar
      tags:
        - mylar
      when: (mylar_enabled | default(False))

    - role: mymediaforalexa
      tags:
        - mymediaforalexa
      when: (mymediaforalexa_enabled | default(False))

    - role: n8n
      tags:
        - n8n_enabled
      when: (n8n_enabled | default(False))

    - role: netbootxyz
      tags:
        - netbootxyz
      when: (netbootxyz_enabled | default(False))

    - role: netdata
      tags:
        - netdata
      when: (netdata_enabled | default(False))

    - role: nextcloud
      tags:
        - nextcloud
      when: (nextcloud_enabled | default(False))

    - role: nzbget
      tags:
        - nzbget
      when: (nzbget_enabled | default(False))

    - role: organizr
      tags:
        - organizr
      when: (organizr_enabled | default(False))

    - role: portainer
      tags:
        - portainer
      when: (portainer_enabled | default(False))

    - role: pyload
      tags:
        - pyload
      when: (pyload_enabled | default(False))

    - role: ombi
      tags:
        - ombi
      when: (ombi_enabled | default(False))

    - role: openhab
      tags:
        - openhab
      when: (openhab_enabled | default(False))

    - role: openvpn-client
      tags:
        - openvpn-client
      when: (openvpn-client_enabled | default(False))

    - role: plex
      tags:
        - plex
      when: (plex_enabled | default(False))

    - role: pytivo
      tags:
        - pytivo
      when: (pytiv_enabled | default(False))

    - role: radarr
      tags:
        - radarr
      when: (radarr_enabled | default(False))

    - role: radarr
      tags:
        - radarr
      when: (radarr_enabled | default(False))

    - role: sickchill
      tags:
        - sickchill
      when: (sickchill_enabled | default(False))

    - role: sonarr
      tags:
        - sonarr
      when: (sonarr_enabled | default(False))

    - role: syncthing
      tags:
        - syncthing
      when: (syncthing_enabled | default(False))

    - role: tautulli
      tags:
        - tautulli
      when: (tautulli_enabled | default(False))

    - role: thelounge
      tags:
        - thelounge
      when: (thelounge_enabled | default(False))

    - role: timemachine
      tags:
        - timemachine
      when: (timemachine_enabled | default(False))

    - role: transmission
      tags:
        - transmission
      when: (transmission_enabled | default(False))

    - role: transmission-with-openvpn
      tags:
        - transmission_with_openvpn
      when: (transmission_with_openvpn_enabled | default(False))

    - role: traefik
      tags:
        - traefik
      when: (traefik_enabled | default(False))

    - role: ubooquity
      tags:
        - ubooquity
      when: (ubooquity_enabled | default(False))

    - role: utorrent
      tags:
        - utorrent
      when: (utorrent_enabled | default(False))

    - role: virtual_desktop
      tags:
        - virtual_desktop
      when: (virtual_desktop_enabled | default(False))

    - role: wallabag
      tags:
        - wallabag
      when: (wallabag_enabled | default(False))

    - role: watchtower
      tags:
        - watchtower
      when: (watchtower_enabled | default(False))

    - role: youtubedlmaterial
      tags:
        - youtubedlmaterial_enabled
      when: (youtubedlmaterial_enabled | default(False))

    - role: znc
      tags:
        - znc
      when: (znc_enabled | default(False))
