---
- hosts: all
  tasks:
  - name: Warning!
    debug:
      msg: "NASible is about to repermission ALL existing data in the shares defined in group_vars/all.yml. If this is not what you want, exit now."

  - name: 20s to change your mind...
    pause:
      seconds: 20

  - name: "Permission share data"
    file:
      path: "{{ item.path }}"
      owner: "{{ nasible_user }}"
      group: "{{ nasible_user }}"
      mode: "u=rwX,g=rwX,o=rX"
      recurse: true
    loop: "{{ samba_shares }}"


