---
- name: Create nasible group
  group:
    name: nasible
    state: present

- name: Create nasible user
  user:
    name: nasible
    state: present
    system: yes
    update_password: on_create
    create_home: no
    group: nasible
    shell: /usr/sbin/nologin
