---
# enable or disable the application
ubooquity_enabled: false
ubooquity_available_externally: "false"

# directories
ubooquity_config_directory: "{{ docker_home }}/ubooquity/config"
ubooquity_logs: "{{ docker_home }}/ubooquity/logs"
ubooquity_share_directory: "{{ example_share_root }}"


# uid / gid
ubooquity_user_id: "0"
ubooquity_group_id: "0"

# network
ubooquity_hostname: "ubooquity"
ubooquity_port: "12345"

# specs
ubooquity_memory: "1g"
