---
- name: Create Ubooquity Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ ubooquity_data_directory }}"

- name: Ubooquity Docker Container
  docker_container:
    name: ubooquity
    image: linuxserver/ubooquity:latest
    pull: true
    volumes:
      - "{{ ubooquity_data_directory }}/config:/config:rw"
      - "{{ ubooquity_data_directory }}/files:/files:rw"
      - "{{ comics_root }}:/comics"
      - "{{ books_root }}:/books"
    env:
      TZ: "{{ nasible_timezone }}"
      PUID: "{{ ubooquity_user_id|quote }}"
      PGID: "{{ ubooquity_group_id|quote }}"
      MAXMEM: "1024"
    ports:
      - "{{ ubooquity_port_webui }}:2202"
      - "{{ ubooquity_port_admin }}:2203"
    restart_policy: unless-stopped
    memory: "{{ ubooquity_memory }}"
    labels:
      traefik.enable: "{{ ubooquity_available_externally }}"
      traefik.http.routers.ubooquity.rule: "Host(`ubooquity.{{ nasible_domain }}`)"
      traefik.http.routers.ubooquity.tls.certresolver: "letsencrypt"
      traefik.http.routers.ubooquity.tls.domains[0].main: "{{ nasible_domain }}"
      traefik.http.routers.ubooquity.tls.domains[0].sans: "*.{{ nasible_domain }}"
      traefik.http.services.ubooquity.loadbalancer.server.port: "2202"
