---
- name: Create Heimdall Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ heimdall_data_directory }}"

- name: Create Heimdall container
  docker_container:
    name: "{{ heimdall_hostname }}"
    image: "{{ heimdall_docker_image }}"
    pull: true
    volumes:
      - "{{ heimdall_data_directory }}:/config:rw"
    env:
      PUID: "{{ heimdall_user_id }}"
      PGID: "{{ heimdall_group_id }}"
      TZ: "{{ nasible_timezone }}"
    ports:
      - "{{ heimdall_port_http }}:80"
      - "{{ heimdall_port_https }}:443"
    restart_policy: unless-stopped
    memory: "{{ heimdall_memory }}"
    labels:
      traefik.enable: "{{ heimdall_available_externally }}"
      traefik.http.routers.heimdall.rule: "Host(`{{ heimdall_hostname }}.{{ nasible_domain }}`)"
      traefik.http.routers.heimdall.tls.certresolver: "letsencrypt"
      traefik.http.routers.heimdall.tls.domains[0].main: "{{ nasible_domain }}"
      traefik.http.routers.heimdall.tls.domains[0].sans: "*.{{ nasible_domain }}"
      traefik.http.services.heimdall.loadbalancer.server.port: "80"