---
- name: Create Calibre Directories
  file:
    path: "{{ item }}"
    state: directory
    # mode: 0755
  with_items:
    - "{{ calibre_data_directory }}/config"

- name: Create Calibre Docker Container
  docker_container:
    name: calibre
    image: linuxserver/calibre-web:latest
    pull: true
    volumes:
      - "{{ calibre_data_directory }}/config:/config"
      - "{{ calibre_books_root }}:/books"
    network_mode: "bridge"
    ports:
      - "{{ calibre_port }}:8083"
    env:
      TZ: "{{ ansible_nas_timezone }}"
      PUID: "{{ calibre_user_id }}"
      PGID: "{{ calibre_group_id }}"
      DOCKER_MODS: "{{ calibre_ebook_conversion }}"
    restart_policy: unless-stopped
    memory: "{{ calibre_memory }}"
    labels:
      traefik.enable: "{{ calibre_available_externally }}"
      traefik.http.routers.calibre.rule: "Host(`{{ calibre_hostname }}.{{ ansible_nas_domain }}`)"
      traefik.http.routers.calibre.tls.certresolver: "letsencrypt"
      traefik.http.routers.calibre.tls.domains[0].main: "{{ ansible_nas_domain }}"
      traefik.http.routers.calibre.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
      traefik.http.services.calibre.loadbalancer.server.port: "8083"
