---
- name: Create Airsonic Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ airsonic_data_directory }}/data"
    - "{{ airsonic_playlists_directory }}/airsonic"
    - "{{ airsonic_logs }}"

- name: Create Airsonic Docker Container
  docker_container:
    name: "{{ airsonic_name }}"
    image: "{{ airsonic_image }}"
    pull: true
    volumes:
      - "{{ airsonic_data_directory }}:/var/airsonic:rw"
      - "{{ airsonic_playlists_directory }}/airsonic:/var/playlists:rw"
      - "{{ airsonic_music_directory }}:/var/music:rw"
      - "{{ airsonic_podcasts_directory }}:/var/podcasts:rw"
    domainname: "{{ airsonic_domain }}"
    hostname: "{{ airsonic_hostname }}"
    network_mode: "{{ airsonic_network_mode }}"
    ports:
      - "{{ airsonic_port_web }}:4040"
      - "{{ airsonic_port_upnp }}:4041"
    restart_policy: "{{ airsonic_restarts }}"
    env:
      TZ: "{{ nasible_timezone }}"
      PUID: "{{ airsonic_user_id }}"
      PGID: "{{ airsonic_group_id }}"
    cpuset_cpus: "{{ airsonic_cpus }}"
    memory: "{{ airsonic_memory }}"
    labels:
      traefik.enable: "{{ airsonic_available_externally }}"
      traefik.http.routers.airsonic.rule: "Host(`{{ airsonic_hostname }}.{{ nasible_domain }}`)"
      traefik.http.routers.airsonic.tls.certresolver: "letsencrypt"
      traefik.http.services.airsonic.loadbalancer.server.port: "4040"
