---
- name: Create Airsonic Directories
  file:
    path: "{{ item }}"
    state: directory
    # mode: 0755
  with_items:
    - "{{ airsonic_data_directory }}/data"
    - "{{ airsonic_playlists_directory }}/playlists"

- name: Create Airsonic Docker Container
  docker_container:
    name: "{{ airsonic_hostname }}"
    image: airsonicadvanced/airsonic-advanced:latest
    pull: true
    volumes:
      - "{{ airsonic_data_directory }}:/var/data:rw"
      - "{{ airsonic_data_directory }}/playlists:/var/playlists:rw"
      - "{{ airsonic_music_directory }}:/var/music:rw"
      - "{{ airsonic_podcasts_directory }}:/var/podcasts:rw"
    ports:
      - "{{ airsonic_port }}:4040"
    restart_policy: unless-stopped
    memory: "{{ airsonic_memory }}"
    labels:
      traefik.enable: "{{ airsonic_available_externally }}"
      traefik.http.routers.airsonic.rule: "Host(`{{ airsonic_hostname }}.{{ nasible_domain }}`)"
      traefik.http.routers.airsonic.tls.certresolver: "letsencrypt"
      traefik.http.routers.airsonic.tls.domains[0].main: "{{ nasible_domain }}"
      traefik.http.routers.airsonic.tls.domains[0].sans: "*.{{ nasible_domain }}"
      traefik.http.services.airsonic.loadbalancer.server.port: "4040"
