---
- name: Create Nextcloud directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ nextcloud_data_directory }}/nextcloud"
    - "{{ nextcloud_data_directory }}/mysql"

- name: Nextcloud Mysql Docker Container
  docker_container:
    name: "{{ nextcloud_hostname }}-mysql"
    image: mysql
    pull: true
    volumes:
      - "{{ nextcloud_data_directory }}/mysql:/var/lib/mysql:rw"
    env:
      MYSQL_DATABASE: "nextcloud"
      MYSQL_USER: "{{ nextcloud_sql_user }}"
      MYSQL_PASSWORD: "{{ nextcloud_sql_password }}"
      MYSQL_ROOT_PASSWORD: "{{ nextcloud_sql_root_password }}"
    restart_policy: unless-stopped
    memory: 2g

- name: Nextcloud Docker Container
  docker_container:
    name: "{{ nextcloud_hostname }}"
    image: "{{ nextcloud_image }}"
    pull: true
    links:
      - "{{ nextcloud_hostname }}-mysql:mysql"
    volumes:
      - "{{ nextcloud_data_directory }}/nextcloud:/var/www/html:rw"
    ports:
      - "{{ nextcloud_port }}:80"
    env:
      MYSQL_HOST: "mysql"
      MYSQL_DATABASE: "nextcloud"
      MYSQL_USER: "{{ nextcloud_sql_user }}"
      MYSQL_PASSWORD: "{{ nextcloud_sql_password }}"
      NEXTCLOUD_TRUSTED_DOMAINS: "{{ nextcloud_hostname }}.{{ nasible_domain }}"
    restart_policy: unless-stopped
    memory: "{{ nextcloud_memory }}"
    labels:
      traefik.enable: "{{ nextcloud_available_externally }}"
      traefik.http.routers.nextcloud.rule: "Host(`{{ nextcloud_hostname }}.{{ nasible_domain }}`)"
      traefik.http.routers.nextcloud.tls.certresolver: "letsencrypt"
      traefik.http.routers.nextcloud.tls.domains[0].main: "{{ nasible_domain }}"
      traefik.http.routers.nextcloud.tls.domains[0].sans: "*.{{ nasible_domain }}"
      traefik.http.services.nextcloud.loadbalancer.server.port: "80"
