---
# enable or disable the application
mosquitto_enabled: false
mosquitto_available_externally: "false"

# directories
mosquitto_config_directory: "{{ docker_home }}/mosquitto/config"
mosquitto_logs: "{{ docker_home }}/mosquitto/logs"
mosquitto_share_directory: "{{ example_share_root }}"


# uid / gid
mosquitto_user_id: "0"
mosquitto_group_id: "0"

# network
mosquitto_hostname: "mosquitto"
mosquitto_port: "12345"

# specs
mosquitto_memory: "1g"
