{
 "title": "NASible Overview",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "server",
    "label": "Server",
    "query": "SHOW TAG VALUES FROM system WITH KEY=host"
   },
   {
    "name": "zfs_pool",
    "label": "ZFS Pool",
    "query": "SHOW TAG VALUES FROM zfs_pool WITH KEY=pool"
   },
   {
    "name": "physical_disk",
    "label": "Physical Disk",
    "query": "SHOW TAG VALUES FROM diskio WITH KEY=\"name\""
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "CPUs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "n_cpus" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT (100 - last(\"usage_idle\")) FROM \"cpu\" WHERE (\"host\" =~ /^$server$/ AND \"cpu\" = 'cpu-total') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "usage_idle" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "cpu", "operator": "=", "value": "cpu-total" }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "RootFS used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "path", "operator": "=", "value": "/" }
     ]
    }
   ]
  },
  {
   "title": "Swap Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"used_percent\") FROM \"swap\" WHERE (\"host\" =~ /^$server$/) AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Running Containers",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker",
     "select": [
      [
       { "params": [ "n_containers_running" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "CPU Utilisation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "user" ], "type": "alias" }
      ],
      [
       { "params": [ "usage_system" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "system" ], "type": "alias" }
      ],
      [
       { "params": [ "usage_iowait" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "iowait" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "cpu", "operator": "=", "value": "cpu-total" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "load1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "load1" ], "type": "alias" }
      ],
      [
       { "params": [ "load5" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "load5" ], "type": "alias" }
      ],
      [
       { "params": [ "load15" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "load15" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "used" ], "type": "alias" }
      ],
      [
       { "params": [ "cached" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "cached" ], "type": "alias" }
      ],
      [
       { "params": [ "buffered" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "buffered" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  { "title": "Docker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Container CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_container_name",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "container_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_cpu",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Container Memory usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_container_name",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "container_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_mem",
     "select": [
      [
       { "params": [ "usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  { "title": "Temperature", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "System Temperature",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "$tag_chip - $tag_feature",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "chip" ], "type": "tag" },
      { "params": [ "feature" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sensors",
     "select": [
      [
       { "params": [ "temp_input" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk Temperature",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "$tag_device - $tag_model",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "model" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hddtemp",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "device", "operator": "=~", "value": "/^$physical_disk$/" }
     ]
    }
   ]
  },
  { "title": "ZFS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Pool $zfs_pool Data I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 41 },
   "repeat": "zfs_pool",
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "zfs_pool",
     "query": "SELECT difference(mean(\"nread\")) AS \"Data Read\" FROM \"zfs_pool\" WHERE (\"pool\" =~ /^$zfs_pool$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "nread" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "Data Read" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "pool", "operator": "=~", "value": "/^$zfs_pool$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "zfs_pool",
     "query": "SELECT difference(mean(\"nread\")) AS \"Data Read\" FROM \"zfs_pool\" WHERE (\"pool\" =~ /^$zfs_pool$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "nwritten" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "Data Written" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "pool", "operator": "=~", "value": "/^$zfs_pool$/" }
     ]
    }
   ]
  },
  {
   "title": "Pool $zfs_pool Iops",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 41 },
   "repeat": "zfs_pool",
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "zfs_pool",
     "query": "SELECT difference(mean(\"nread\")) AS \"Data Read\" FROM \"zfs_pool\" WHERE (\"pool\" =~ /^$zfs_pool$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "reads" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "Data Read" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "pool", "operator": "=~", "value": "/^$zfs_pool$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "zfs_pool",
     "query": "SELECT difference(mean(\"nread\")) AS \"Data Read\" FROM \"zfs_pool\" WHERE (\"pool\" =~ /^$zfs_pool$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "writes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "Data Written" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "pool", "operator": "=~", "value": "/^$zfs_pool$/" }
     ]
    }
   ]
  },
  {
   "title": "Pool $zfs_pool Data I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "zfs_pool",
     "query": "SELECT difference(mean(\"nread\")) AS \"Data Read\" FROM \"zfs_pool\" WHERE (\"pool\" =~ /^$zfs_pool$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "nread" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "Data Read" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "pool", "operator": "=~", "value": "/^$zfs_pool$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "zfs_pool",
     "query": "SELECT difference(mean(\"nread\")) AS \"Data Read\" FROM \"zfs_pool\" WHERE (\"pool\" =~ /^$zfs_pool$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "nwritten" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "Data Written" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "pool", "operator": "=~", "value": "/^$zfs_pool$/" }
     ]
    }
   ]
  },
  {
   "title": "Pool $zfs_pool Iops",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "zfs_pool",
     "query": "SELECT difference(mean(\"nread\")) AS \"Data Read\" FROM \"zfs_pool\" WHERE (\"pool\" =~ /^$zfs_pool$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "reads" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "Data Read" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "pool", "operator": "=~", "value": "/^$zfs_pool$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "zfs_pool",
     "query": "SELECT difference(mean(\"nread\")) AS \"Data Read\" FROM \"zfs_pool\" WHERE (\"pool\" =~ /^$zfs_pool$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "writes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "Data Written" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "pool", "operator": "=~", "value": "/^$zfs_pool$/" }
     ]
    }
   ]
  },
  { "title": "Physical Disks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "$physical_disk Data I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 56 },
   "repeat": "physical_disk",
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "read_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "Read" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$physical_disk$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "write_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "Write" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$physical_disk$/" }
     ]
    }
   ]
  },
  {
   "title": "$physical_disk Disk Iops",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 56 },
   "repeat": "physical_disk",
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "reads" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "Read" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$physical_disk$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "writes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "Write" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$physical_disk$/" }
     ]
    }
   ]
  },
  {
   "title": "$physical_disk Data I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "read_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "Read" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$physical_disk$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "write_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "Write" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$physical_disk$/" }
     ]
    }
   ]
  },
  {
   "title": "$physical_disk Disk Iops",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 63 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "reads" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "Read" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$physical_disk$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "writes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "Write" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$physical_disk$/" }
     ]
    }
   ]
  },
  {
   "title": "$physical_disk Data I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "read_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "Read" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$physical_disk$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "write_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "Write" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$physical_disk$/" }
     ]
    }
   ]
  },
  {
   "title": "$physical_disk Disk Iops",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 70 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "reads" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "Read" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$physical_disk$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "writes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "Write" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$physical_disk$/" }
     ]
    }
   ]
  },
  {
   "title": "$physical_disk Data I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "read_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "Read" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$physical_disk$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "write_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "Write" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$physical_disk$/" }
     ]
    }
   ]
  },
  {
   "title": "$physical_disk Disk Iops",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 77 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "reads" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "Read" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$physical_disk$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "writes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "Write" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$physical_disk$/" }
     ]
    }
   ]
  },
  {
   "title": "$physical_disk Data I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 84 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "read_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "Read" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$physical_disk$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "write_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "Write" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$physical_disk$/" }
     ]
    }
   ]
  },
  {
   "title": "$physical_disk Disk Iops",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 84 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "reads" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "Read" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$physical_disk$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "writes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "Write" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$physical_disk$/" }
     ]
    }
   ]
  }
 ]
}