---
- name: Create Gotify Data Directory
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ gotify_data_directory }}"

- name: Gotify Docker Container
  docker_container:
    name: gotify
    image: "{{ gotify_docker_image }}"
    pull: true
    ports:
      - "{{ gotify_port }}:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "{{ gotify_data_directory }}:/app/data:rw"
    env:
      TZ: "{{ nasible_timezone }}"
      PUID: "{{ gotify_user_id }}"
      PGID: "{{ gotify_group_id }}"
    restart_policy: unless-stopped
    memory: "{{ gotify_memory }}"
    labels:
      traefik.enable: "{{ gotify_available_externally }}"
      traefik.http.routers.gotify.rule: "Host(`{{ gotify_hostname }}.{{ nasible_domain }}`)"
      traefik.http.routers.gotify.tls.certresolver: "letsencrypt"
      traefik.http.routers.gotify.tls.domains[0].main: "{{ nasible_domain }}"
      traefik.http.routers.gotify.tls.domains[0].sans: "*.{{ nasible_domain }}"
      traefik.http.services.gotify.loadbalancer.server.port: "80"
