---
- name: Create Home Assistant Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ homeassistant_data_directory }}/config"

- name: Home Assistant Docker Container
  docker_container:
    name: homeassistant
    image: homeassistant/home-assistant
    pull: true
    volumes:
      - "{{ homeassistant_data_directory }}/config:/config:rw"
    network_mode: host
    restart_policy: unless-stopped
    env:
      TZ: "{{ nasible_timezone }}"
    labels:
      traefik.enable: "{{ homeassistant_available_externally }}"
      traefik.http.routers.homeassistant.rule: "Host(`{{ homeassistant_hostname }}.{{ nasible_domain }}`)"
      traefik.http.routers.homeassistant.tls.certresolver: "letsencrypt"
      traefik.http.routers.homeassistant.tls.domains[0].main: "{{ nasible_domain }}"
      traefik.http.routers.homeassistant.tls.domains[0].sans: "*.{{ nasible_domain }}"
      traefik.http.services.homeassistant.loadbalancer.server.port: "8123"
    memory: "{{ homeassistant_memory }}"
