---
- name: Create Wallabag Directories
  file:
    path: "{{ item }}"
    state: directory
    # mode: 0755
  with_items:
    - "{{ wallabag_data_directory }}/data"
    - "{{ wallabag_data_directory }}/images"

- name: Wallabag Docker Container
  docker_container:
    name: wallabag
    image: wallabag/wallabag:latest
    pull: true
    volumes:
      - "{{ wallabag_data_directory }}/data:/var/www/wallabag/data:rw"
      - "{{ wallabag_data_directory }}/images:/var/www/wallabag/web/assets/images:rw"
    network_mode: "bridge"
    ports:
      - "{{ wallabag_port }}:80"
    env:
      SYMFONY__ENV__DOMAIN_NAME: "https://wallabag.{{ ansible_nas_domain }}"
    restart_policy: unless-stopped
    memory: "{{ wallabag_memory }}"
    labels:
      traefik.enable: "{{ wallabag_available_externally }}"
      traefik.http.routers.wallabag.rule: "Host(`{{ wallabag_hostname }}.{{ ansible_nas_domain }}`)"
      traefik.http.routers.wallabag.tls.certresolver: "letsencrypt"
      traefik.http.routers.wallabag.tls.domains[0].main: "{{ ansible_nas_domain }}"
      traefik.http.routers.wallabag.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
      traefik.http.services.wallabag.loadbalancer.server.port: "80"
